### ISSUE TITLE
gcc won't install on binder

### ISSUE THREAD

**Issue by bjodah** [sympy/scipy-2017-codegen-tutorial#12]
I've reached out on their gitter channel. waiting to see if someone knows why. If it doesn't get solved we'll either have to not use gcc on binder, or provide a dockerimage.

**Comment by moorepants** [comment]
I wouldn't spend too much time on this unless we are planning to have people use it in the tutorial. Is this the planned option for Windows users? Or are we setting this up just because?

**Comment by bjodah** [comment]
I think we said that it would be a good fall-back if some people have trouble installing the conda environment. You're probably right. I'll put this on the back burner for now.

**Comment by moorepants** [comment]
Let's see if we can get the notebooks running consistently on Windows and if not we can switch to binder, a vm, or something else for them. I just got my windows machine fired up and will give it a shot.

**Comment by bjodah** [comment]
OK, so I poked around with a Dockerfile now and then through the day and I got binder working (all notebook works, including compilation).
