### ISSUE TITLE
Culling, Organizing, and Timing for the Content

### ISSUE THREAD

**Issue by moorepants** [sympy/scipy-2017-codegen-tutorial#15]
Kenny and I have been working on judging how much content we have and whether we can fit everything in. To do this we've been creating more detailed outlines of the materials with estimated timings for the sections here:

http://nbviewer.jupyter.org/github/sympy/scipy-2017-codegen-tutorial/blob/master/index.ipynb

I suggested earlier that a good rule of thumb would be alternating sections of 5 minutes talking/explaining to 10 minutes of exercise doing. This is flexible depending on if you want to have very short exercises or longer ones. But exercises should be between 5 and 15 minutes long with an average of 3 medium exercises per hour for a exercise heavy tutorial.

We've moved the extra notebooks to the bonus material area, which students can investigate on their own and we can show off briefly if there is any time at the end.

Can everyone look at their sections and fill out the outline in index.ipynb with estimates of timings?

One thing that looks clear is that the first two 30 minute sections are lean and the section after has four notebooks. Maybe we should move the ode intro into aaron's sections?

**Comment by bjodah** [comment]
+1 for moving the mathematical refresher (i.e. no code-gen) on ODEs to the SymPy intro section.

I just added an exercise for lambdify in notebook 22. Moving the ODE intro to the section before would also make the study case for that exercise easier for the student to grasp.
