### ISSUE TITLE
Kenny's notebook renders with different font on the KTH server

### ISSUE THREAD

**Issue by moorepants** [sympy/scipy-2017-codegen-tutorial#17]
![selection_179](https://user-images.githubusercontent.com/276007/27722129-3c13e3bc-5d1a-11e7-8d4e-fdf40082be28.jpg)

http://hera.physchem.kth.se/~scipy-2017-codegen-tutorial/notebooks/08-the-easy-hard-way.html

**Comment by bjodah** [comment]
this is really weird, I've looked at the generated HTML, the `%%cython --anotate` magic emits a whole new nested `<html></html>` environment. My guess is that the CSS set there clashes somehow. I think we could live with this though?

**Comment by moorepants** [comment]
Yeah we can live with it. Sounds like something that should be reported upstream.

**Comment by bjodah** [comment]
Yeah, let's look into doing that at the conference? (closing for now)
