### ISSUE TITLE
Notes from practice run with SymPy beginner

### ISSUE THREAD

**Issue by bjodah** [sympy/scipy-2017-codegen-tutorial#23]
I got a colleague of mine to try our notebooks. She has got some experience working with Python (6 months), using mainly numpy. She has no prior experience with SymPy, SciPy or cython (so technically she doesn't meet or prerequisites).

The intro notebook took her close to one hour to complete. But she actually got through the material. So overall I think that it is encouraging (the material will be valuable also for those who do not quite meet the requirements).

We only went as long as the "Easy way". I don't have any other colleagues with Python experience I'm afraid so I won't have any empirical timings of the tutorial material. But I suspect that I might have to skip the last notebook in my section (it's not too bad, maybe we should just make people aware that it's expected so that they don't get stressed).

**Comment by moorepants** [comment]
Cool! Nice work. Did you deliver the material live? Or did she just read through and do them?

In each of our sections I think it is ok if we have to stop a bit short. It is better to ensure that people are not lost and learn some of it well than little of the whole thing.

**Comment by asmeurer** [comment]
The intro notebook is supposed to be a refresher for someone who's used SymPy before. So that's good that someone who hasn't used it got through it. Did you use the version updated as of yesterday?

**Comment by bjodah** [comment]
@moorepants she went through them and I supervised (I got some feedback as well - I will move the exercise in the end of the lambidfy notebook to bonus material and replace it with something simpler on the plane tomorrow).

@asmeurer yeah, we ran through it earlier today and I updated master just before.
