### ISSUE TITLE
Binder

### ISSUE THREAD

**Issue by bjodah** [sympy/scipy-2017-codegen-tutorial#3]
building `sympy/scipy-2017-codegen-tutorial` at https://beta.mybinder.org/
generates this cryptic error in the build log:

```
python-symengi 100% |###############################| Time: 0:00:00  21.64 MB/s
qt-5.6.2-3.tar 100% |###############################| Time: 0:00:01  26.23 MB/s
{"phase":"Failed"}% |##########                     | Time: 0:00:00  29.24 MB/s
{"phase":"Failed"}% |###############                | Time: 0:00:00  30.73 MB/s
Build completed, launching...#######                | Time: 0:00:00  30.77 MB/s
```

not sure how to proceed here.

**Comment by moorepants** [comment]
Maybe ask on the binder gitter channel. I have no idea.

**Comment by bjodah** [comment]
No clue what the issue was, anyhow, it's working now:
https://beta.mybinder.org/v2/gh/sympy/scipy-2017-codegen-tutorial/master
