### ISSUE TITLE
Custom package isn't installed

### ISSUE THREAD

**Issue by moorepants** [sympy/scipy-2017-codegen-tutorial#4]
The enviroment.yml file is very nice way to get everyone setup but it doesn't install the custom package in the repo. Apparently you can add something like `pip install -e .` to the environment.yml as a fix. Other options are to make it a real conda package or just put some kind of `sys.path.append(...)` calls before imports in the notebooks.

**Comment by bjodah** [comment]
It is already a real conda package:
https://anaconda.org/SymPy/scipy2017codegen

But if you are making changes to it locally you should remove the last line of `environment.yml` and run e.g. `python setup.py develop` (for some reason `pip install -e .` failed on one of the CI servers, can't remember which). Or do `export PYTHONPATH=$(pwd):$PYTHONPATH`, or as you said: `sys.path.append(...)`

**Comment by moorepants** [comment]
Oh good. So I'm not sure why it didin't get installed when I ran the environment.yml command. I'll dig around.

**Comment by bjodah** [comment]
I just updated the README to hopefully clarify this.
