### ISSUE TITLE
tutorial.md or wiki?

### ISSUE THREAD

**Issue by bjodah** [sympy/scipy-2017-codegen-tutorial#9]
I copied over the proposal from the wiki to this repo (tutorial.md).
I see we have link to the wiki now in the README. I guess we should remove one of those? (either is fine by me)

**Comment by moorepants** [comment]
We can keep the wiki page as is, that proposal was already submitted, but we can modify that content for use in this repo. I'd rather see it in the README and the index.ipynb file, as those places are the first two likely places for users to land.
